version: "3"

services:
  haproxy:
    
    image: docker-project-haproxy
    
    container_name: haproxy
    networks:
      - my_network
    ports:
      - "80:80"  # Expose HAProxy port 80 to the host

  nginx1:
    image: docker-project-nginx1
    container_name: nginx1
    networks:
      - my_network
    expose:
      - "80"  # Expose port 80 within the Docker network for HAProxy to reach
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure


  nginx2:
    image: docker-project-nginx2
    container_name: nginx2
    networks:
      - my_network
    expose:
      - "80"  # Expose port 80 within the Docker network for HAProxy to reach
    deploy:
      replicas: 2  # Scale nginx2 service to 3 replicas
      restart_policy:
        condition: on-failure

  varnish:
    image: docker-project-varnish
    container_name: varnish
    networks:
      - my_network
    ulimits:
     memlock:
      soft: -1  # Unlimited soft lock limit
      hard: -1  # Unlimited hard lock limit
    expose:
      - "80"

networks:
  my_network:
    driver: overlay

